### PR TITLE
Update to latest version

### PR DESCRIPTION
**Pull request by djechelon**
Proposed update to most recent stable version (see https://github.com/lorenzofox3/Smart-Table/releases). WARNING: this requires updating AngularJS webjar to 1.4.4. I will PR in a few minutes that change

### CODE REVIEW

**Comment by djechelon** [comment]
No sorry I think I made a mistake. Latest version of Angular is **not** required. I will keep them separated (and redo the PR)

**Comment by jamesward** [comment]
For future reference you can always update a PR by pushing your changes to your branch instead of creating a new PR.

**Comment by djechelon** [comment]
Sure, I know. But since I wanted to revert a change I did I preferred to keep history clean :smile:

**Comment by jamesward** [comment]
You can always rebase or do whatever you want to the history and force push over your branch.

**Pull request closed without merging**
